config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root 'chats#index'
  
  # resources :chats do
  #    post 'messages', to: 'messages#create'
  # end 
  namespace 'api' do
    namespace 'v1' do
      resources :chats
      resources :chats do
          post 'messages', to: 'messages#create'
      end
      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chat.rb
class Chat < ApplicationRecord
    has_many :messages
end
#uwu2

app/controllers/api/v1/chats_controller.rb
module Api
    module V1
        class ChatsController < ApplicationController
            protect_from_forgery with: :null_session
            before_action :set_chat, only: [:show, :edit, :update, :destroy]
            before_action :authenticate_and_load_user
          
            # GET /chats
            # GET /chats.json
            def index
              @chats = Chat.all
              render json: {
                  messages: "Request Successfull!",
                  is_success: true,
                  data: { chats: @chats }
              }
            end

            def create
                @chat = Chat.new(chat_params)

                respond_to do |format|
                    if @chat.save
                        format.json { render json: {
                            messages: "Request Successfull!",
                            is_success: true,
                            data: { chat: @chat }
                        } }
                    else
                        format.json { render json: {
                            messages: "Bad Request!",
                            is_success: false,
                            data: { }
                        } }
                    end
                end
            end

            def show
                @messages = @chat.messages
                messages_copy = []
                @messages.each { |message|
                    message_copy = message.attributes
                    username = User.find(message.user_id).username
                    message_copy[:username] = username
                    messages_copy << message_copy
                }
                render json: {
                    messages: "Request Successfull!",
                    is_success: true,
                    data: { messages: messages_copy }
                }
            end
          
            private
              # Use callbacks to share common setup or constraints between actions.
              def set_chat
                @chat = Chat.find(params[:id])
              end
          
              # Only allow a list of trusted parameters through.
              def chat_params
                params.require(:chat).permit(:title)
              end

              def authenticate_and_load_user
                authentication_token = nil
                if request.headers["Authorization"]
                    authentication_token = request.headers["Authorization"].split[1]
                end
                if authentication_token
                    @current_user = User.find_by(auth_token: authentication_token)
                end
                return if @current_user.present?
                render json: {
                    messages: "Can't authenticate user",
                    is_success: false,
                    data: {}
                  }, status: :bad_request
              end
          end          
    end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /chats
  # GET /chats.json
  def index
    @chats = Chat.all
  end

  # GET /chats/1
  # GET /chats/1.json
  def show
    @message = Message.new
    @messages = @chat.messages
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats
  # POST /chats.json
  def create
    @chat = Chat.new(chat_params)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to @chat, notice: 'Chat was successfully created.' }
        format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1
  # PATCH/PUT /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to @chat, notice: 'Chat was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    @chat.destroy
    respond_to do |format|
      format.html { redirect_to chats_url, notice: 'Chat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chat_params
      params.require(:chat).permit(:title)
    end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_form.html.erb
<%= simple_form_for(@chat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Editing Chat</h1>

<%= render 'form', chat: @chat %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<%= link_to 'New Chat', new_chat_path %>


<div class="row">
<div class="col-xs-6 col-centrada" style="width: 60vh; height:80vh; overflow-y: auto;">


      <h1>Chat Rooms</h1>     
    <% @chats.each do |chat| %>
     
      <div class="card-container">
      <div class="card">
        <div class="front">
          <%= chat.title %>
        </div>
        <%= link_to 'JOIN', chat %>
      </div>
    </div>
    <% end %>
</div>
</div>

app/views/chats/new.html.erb
<h1>New Chat</h1>

<%= render 'form', chat: @chat %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<h1>
  <%= @chat.title %>
</h1>

<%= link_to 'Back', chats_path %>

<div class="row">
  <div class="col-x-6 col-centrada" style="width: 500px; height:70vh; overflow-y: auto;">


    <% @messages.each do |msg| %>
      <div class="msgbox">
          <div class="msg-data">
            <div class="msg-name"><%= msg.user.username %></div>
            <div class="msg-time">[<%= msg.created_at %>] :</div>
          </div>
          <div class="msg-body">
              <%= msg.body %>
          </div>
      </div>
    <% end %>
  </div>
</div>

<div class="mx-auto" style=" width: 500px;">
  <%= form_with model: [@chat, @message], local: true, html: { autocomplete: "off" } do |f| %>
  <%= f.text_field :body, class: "client-request"%>
  <%= f.submit "Send" %>
</div>
<% end %>